суммировали два значения
js-tasks-ru/jsbasic-20220124_snl290995 pull request #1
Opened 2022-01-24 17:21 UTC by EdWrightwesr

2022-01-24 17:21 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2022-01-25 05:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-25 05:07 UTC, koalex requested changes
Исправить `alert` на `return`

2022-01-25 05:07 UTC, koalex commented on 0-module/1-task/index.js
> +    alert(m + n);
`return m + n;`

2022-01-26 06:06 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-01-26 06:07 UTC, koalex approved these changes

2022-01-26 06:07 UTC, koalex commented on 0-module/1-task/index.js
> +alert (result);
Удалить эти `alert`-ы в след коммите

2022-01-26 06:07 UTC, merged